management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true
      show-details: never


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-first-mongo-db